Fix TS2839 issue in FaustAudioProcessorNode.ts
src/FaustAudioProcessorNode.ts(263,9): error TS2839: This condition will always return 'true' since JavaScript compares objects by reference, not value.