fix FaustAudioProcessorNode.ts issue
src/FaustAudioProcessorNode.ts(263,9): error TS2839: This condition will always return 'true' since JavaScript compares objects by reference, not value.